version: '3.8'

services:
  db:
    image: postgres:15
    container_name: payment-db
    restart: always
    environment:
      POSTGRES_USER: ilhan
      POSTGRES_PASSWORD: password
      POSTGRES_DB: paymentdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: payment-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"

volumes:
  db_data:
